import os

LINKEDIN_SCRAPER_PROXY = os.getenv(
    "LINKEDIN_SCRAPER_PROXY", None,
)
LINKEDIN_SCRAPER_GOOGLE_CONCURRENCY = os.getenv(
    "LINKEDIN_SCRAPER_GOOGLE_CONCURRENCY", 20
)
LINKEDIN_SCRAPER_LINKEDIN_CONCURRENCY = os.getenv(
    "LINKEDIN_SCRAPER_LINKEDIN_CONCURRENCY", 10
)
LINKEDIN_SCRAPER_MAX_GOOGLE_RETRY = os.getenv("LINKEDIN_SCRAPER_MAX_GOOGLE_RETRY", 3)
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO")
LOGGER_NAME = "linkedinscraper_logger"
